language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

cache:
  directories:
  - "$HOME/.composer"

before_install:
  - composer validate

install:
  - composer install --no-interaction -o --no-suggest

script:
  - php -l src/
  - composer check-syntax
